services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: wpnpc
      POSTGRES_PASSWORD: password;)
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
