services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: whirlpool_beep_dev
      POSTGRES_PASSWORD: whirlpool_beep_password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
